// libs/demo-lib-qwik/src/Canvas.tsx
import { component$, useVisibleTask$, useSignal, $, noSerialize, QRL } from '@builder.io/qwik'

interface CanvasProps {
  setup?: QRL<(ctx: CanvasRenderingContext2D, canvas: HTMLCanvasElement) => void>
  draw?: QRL<(ctx: CanvasRenderingContext2D, canvas: HTMLCanvasElement, frameCount: number) => void>
}

interface Dimensions {
  width: number
  height: number
}

export const Canvas = component$<CanvasProps>(({ setup, draw }) => {
  const containerRef = useSignal<HTMLDivElement>()
  const canvasRef = useSignal<HTMLCanvasElement>()
  const frameCount = useSignal(0)
  const renderer = useSignal<QRL<() => void>>()

  useVisibleTask$(async ({ cleanup }) => {
    const container = containerRef.value
    const canvas = canvasRef.value

    if (!canvas) return
    if (!container) return

    const ctx = noSerialize(canvas.getContext('2d')!)
    if (!ctx) return

    // let animationFrameId: number;

    const handleResize = $(() => {
      const scale = window.devicePixelRatio
      const width = container.clientWidth
      const height = container.clientHeight
      canvas.width = width * scale
      canvas.height = height * scale
      ctx.scale(scale, scale)
    })

    renderer.value = $(function () {
      frameCount.value++
      ctx.fillStyle = 'black'
      ctx.fillRect(0, 0, canvas.width, canvas.height)
      if (draw) {
        draw(ctx, canvas, frameCount.value)
      }

      window.requestAnimationFrame(async () => await renderer.value!())
    })

    await handleResize()
    window.addEventListener('resize', () => handleResize())

    if (setup) {
      await setup(ctx, canvas)
    }

    await renderer.value()

    cleanup(() => {
      window.removeEventListener('resize', () => handleResize())
      // window.cancelAnimationFrame(animationFrameId);
    })
  })

  return (
    <div ref={containerRef} class="canvas-container w-full h-full flex flex-col items-stretch justify-stretch overflow-hidden">
      <canvas
        ref={canvasRef}
      />
    </div>
  )
})

// libs/demo-lib-react/src/react/Canvas.tsx
import React, { useRef, useEffect, useState } from 'react'

interface CanvasProps {
    setup?: (ctx: CanvasRenderingContext2D, canvas: HTMLCanvasElement) => void
    draw?: (ctx: CanvasRenderingContext2D, canvas: HTMLCanvasElement, frameCount: number) => void
}

interface Dimensions {
    width: number
    height: number
}

export const Canvas: React.FC<CanvasProps> = ({
    setup,
    draw,
}) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const canvasRef = useRef<HTMLCanvasElement>(null)
    const [_, setDimensions] = useState<Dimensions>({ width: 0, height: 0 })

    useEffect(() => {
        const container = containerRef.current
        const canvas = canvasRef.current

        if (!canvas) return
        if (!container) return

        const ctx = canvas.getContext('2d')
        if (!ctx) return

        let animationFrameId: number
        let frameCount = 0

        const handleResize = () => {
            const scale = window.devicePixelRatio
            const width = container.clientWidth
            const height = container.clientHeight

            setDimensions({ width, height })

            canvas.width = width * scale
            canvas.height = height * scale
            ctx.scale(scale, scale)
        }

        const render = () => {
            frameCount++
            ctx.fillStyle = 'black'
            ctx.fillRect(0, 0, canvas.width, canvas.height)

            if (draw) {
                draw(ctx, canvas, frameCount)
            }

            animationFrameId = window.requestAnimationFrame(render)
        }

        handleResize()
        window.addEventListener('resize', handleResize)

        if (setup) {
            setup(ctx, canvas)
        }

        render()

        return () => {
            window.removeEventListener('resize', handleResize)
            window.cancelAnimationFrame(animationFrameId)
        }
    }, [setup, draw])

    return (
        <div ref={containerRef} className="canvas-container w-full h-full flex flex-col items-stretch justify-stretch overflow-hidden">
            <canvas
                ref={canvasRef} />
        </div>
    )
}
